# Generated by Django 4.2.6 on 2023-10-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pig_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pNo', models.IntegerField()),
                ('now', models.DateTimeField()),
                ('act', models.FloatField()),
                ('pred', models.BooleanField()),
            ],
        ),
    ]
